FROM alpine:latest

ENV PIP_BREAK_SYSTEM_PACKAGES=1
ENV BACKGROUND_COLOR="blue"

RUN apk update && \
    apk add --no-cache python3 py3-pip && \
    pip3 install --no-cache --upgrade pip setuptools && \
    ln -sf python3 /usr/bin/python

RUN apk add --no-cache curl

WORKDIR /app

COPY ./app/ .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "app.py"]