FROM python:3.9-slim

RUN apt-get update && \ 
    apt-get install -y --no-install-recommends curl && \ 
    rm -rf /var/lib/apt/lists/*

ENV BACKGROUND_COLOR="blue"

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "app.py"]